# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - publish: .
    artifact: api-platform-$(Build.BuildNumber)
