name: Lint

on: push

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pip install poetry

      - name: Cache poetry packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

      - name: Install poetry packages
        run: poetry install

      - name: Lint python
        run: poetry run flake8 **/*.py

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v1

      - name: Validate Terraform Files
        run: |
          terraform init
          terraform validate
