name: Lint

on: push

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pip install poetry

      - name: Cache poetry packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

      - name: Install poetry packages
        run: poetry install

      - name: Lint python
        run: poetry run flake8 **/*.py

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v1

      - name: Install Apigee Provider
        run: |
          mkdir -p ~/.terraform.d/plugins
          wget https://github.com/zambien/terraform-provider-apigee/releases/download/v0.0.21/terraform-provider-apigee_0.0.21_linux_amd64.tar.gz -O ~/.terraform.d/plugins/terraform.tar.gz
          tar -xzf ~/.terraform.d/plugins/terraform.tar.gz -C ~/.terraform.d/plugins
          ls ~/.terraform.d/plugins

      - name: Initialise Terraform
        run: terraform init -backend=false

      - name: Validate Terraform Files
        run: terraform validate
